/*
 * File: app/store/SeasonStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TestModule.store.SeasonStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'SeasonStore',
            proxy: {
                type: 'ajax',
                url: '/TestModule/StoreResource.php?action=loadSeasons',
                reader: {
                    type: 'json',
                    root: 'rows'
                }
            },
            fields: [
                {
                    name: 'Season',
                    type: 'string'
                }
            ],
            listeners: {
                beforeload: {
                    fn: me.onJsonstoreBeforeLoad,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onJsonstoreBeforeLoad: function(store, operation, eOpts) {
        var seriesCombo = Ext.ComponentQuery.query('#seriesCombo')[0];

        if (seriesCombo && seriesCombo.getValue()) {

            operation.params = {
                'SeriesID' : seriesCombo.getValue()
            };

            return true;
        }
        return false;
    }

});