/*
 * File: app/store/SeriesStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TestModule.store.SeriesStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            storeId: 'SeriesStore',
            proxy: {
                type: 'ajax',
                url: '/TestModule/StoreResource.php?action=loadSeries',
                reader: {
                    type: 'json',
                    root: 'rows'
                }
            },
            fields: [
                {
                    name: 'SeriesID',
                    type: 'int'
                },
                {
                    name: 'SeriesTitle',
                    type: 'string'
                },
                {
                    name: 'SeriesBanner',
                    type: 'string'
                }
            ]
        }, cfg)]);
    }
});